# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8082/payment/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtdXJhZGFiYmFzemFkZTA5OEBnbWFpbC5jb20iLCJyb2xlcyI6IlJPTEVfVVNFUiIsImlhdCI6MTY3NzU2NTE3MSwiZXhwIjoxNjc3NTgzMTcxfQ.TXExCybD8PPCHjgm2YCnM6qESboRioVFWw5jUgJB1Sk

{
  "url": "https://api.stripe.com/v1/payment_intents",
  "method": "post",
  "parameters": {
    "amount": 2000,
    "confirm": "true",
    "currency": "usd",
    "description": "(created by Stripe CLI)",
    "payment_method": "pm_card_visa",
    "payment_method_types": [
      "card"
    ],
    "shipping": {
      "name": "Jenny Rosen",
      "address": {
        "line1": "510 Townsend St",
        "postal_code": "94103",
        "city": "San Francisco",
        "state": "CA",
        "country": "US"
      }
    }
  }
}
###